<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%tour}}`.
 */
class m250703_160542_create_tour_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%tour}}', [
            'id' => $this->primaryKey(),
            'name' => $this->string()->notNull()->comment('Название тура'),
            'price' => $this->integer()->unsigned()->notNull()->comment('Цена тура'),
            'description' => $this->text()->null()->comment('Описание тура'),
            'travel_style' => $this->text()->null()->comment('Стиль путешествия'),
            'service_level' => $this->text()->null()->comment('Уровень обслужования'),
            'physical_rating' => $this->text()->null()->comment('Уровень сложности'),
            'trip_type' => $this->text()->null()->comment('Тип поездки'),
            'age_requirement' => $this->text()->null()->comment('Возраст'),
            'start_date' => $this->date()->comment('Дата начала'),
            'country_id' => $this->integer()->notNull()->comment('Страна'),
            'duration' => $this->integer()->unsigned()->notNull()->comment('Продолжительность тура'),
            'logo_img' => $this->string()->comment('Карта тура'),
        ]);

        $this->addForeignKey(
            'fk-tour-country_id',
            '{{%tour}}',
            'country_id',
            '{{%country}}',
            'id',
            'CASCADE',
            'CASCADE'
        );

        $this->batchInsert('{{%tour}}', ['name', 'price', 'description', 'travel_style', 'service_level', 'physical_rating', 'trip_type', 'age_requirement', 'start_date', 'country_id', 'duration', 'logo_img'], [
            [
                'Canadian Rockies: National Parks Eastbound',
                1770,
                "Now's the time to explore western Canada on your terms with this tour that's affordable for young travellers. Discover that big mountain mood on this journey along the Pacific Coast from Vancouver to the Canadian Rockies...",
                '18-to-Thirtysomethings',
                'Camping',
                '3 - Average',
                'Small Group',
                '18-39',
                '2025-08-18',
                \common\models\Country::findOne(['name' => 'Canada'])->id, // Canada
                14,
                'canada_1.png'
            ],
            [
                'Canadian Rockies Express',
                1819,
                "Marvel at the natural wonders of the Canadian Rockies on this eight-day tour filled with postcard-perfect landscapes. See the pristine waters of Lake Louise and gaze in awe at the mountains in Banff and Whistler...",
                'Classic',
                'Standard',
                '3 - Average',
                'Small Group',
                '12+',
                null,
                \common\models\Country::findOne(['name' => 'Canada'])->id, // Canada
                8,
                'canada_2.png'
            ],
            [
                'Eastern Canada: Highlights of the Maritimes & Newfoundland',
                6299,
                "Get ready for one epic East Coast adventure through Canada’s most charming and rugged provinces. Start your journey in the Maritimes, where you’ll wander the historic streets of Halifax and Charlottetown...",
                'Classic',
                'Standard',
                '3 - Average',
                'Small Group',
                '12+',
                '2026-07-04',
                \common\models\Country::findOne(['name' => 'Canada'])->id, // Canada
                18,
                'canada_3.png'
            ],
            [
                'Alaska Kenai & Denali Adventure',
                1854,
                "For travellers looking to explore a more remote corner of North America at a faster (and more active) pace, this eight-day journey through Alaska's vast vistas is just the ticket. Catch the state's greatest highlights including the imposing Harding Icefield, the enchanting Kenai Fjords, the jaw-dropping Denali National Park, and the charming town of Talkeetna.",
                'Classic',
                'Standard',
                '3 - Average',
                'Small Group',
                '12+',
                '2025-08-21',
                \common\models\Country::findOne(['name' => 'United States'])->id,
                8,
                'usa_1.png'
            ],
            [
                'Southwest Road Trip: Zion, the Grand Canyon & Santa Monica Sunsets',
                999,
                "An American Southwest Special, this trip encompasses some of the absolute best spots in the United States. Featuring deserts, canyons, hoodoos and beaches, this seven-day adventure takes you through four National Parks as you soak up nature at its very finest.",
                'Roamies by Hostelworld & CanadaWay',
                'Camping',
                '3 - Average',
                'Small Group',
                '18-35',
                '2026-07-28',
                \common\models\Country::findOne(['name' => 'United States'])->id,
                7,
                'usa_2.png',
            ],
            [
                'Yellowstone Camping Explorer',
                1749,
                "Get your blood pumping and your heart thumping on this active adventure through the heart of the American West. Spend six days discovering the untamed beauty and wildness of Yellowstone and Grand Teton National Parks. Awaken your inner explorer and use your own two feet to reach new heights on epic hikes through the varied landscapes of Wyoming.",
                'Active',
                'Camping',
                '3 - Average',
                'Small Group',
                '12+',
                '2025-07-27',
                \common\models\Country::findOne(['name' => 'United States'])->id,
                6,
                'usa_3.png'
            ],
            [
                'Central American Journey: Rainforests & Ruins',
                2357,
                "Escape the resorts and discover something extraordinary in Central America. Visit seven countries on this adventure and experience mighty ruins, clear Caribbean waters, Pacific waves, rainforests, and breathtaking scenery. Explore indigenous Mayan villages and meet locals for an immersive experience.",
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-11-27',
                \common\models\Country::findOne(['name' => 'Belize'])->id,
                32,
                'belize_1.png'
            ],
            [
                'Central America in Seven Countries: Mexico to Costa Rica',
                2449,
                "Are you looking for the maximum Central American adventure at minimum cost? This 32-day trip includes Mayan ruins, Caribbean waters, lush rainforests, and Pacific waves. Includes lots of optional activities and cultural immersion.",
                'Classic',
                'Basic',
                '2 - Light',
                'Small Group',
                '12+',
                '2025-09-04',
                \common\models\Country::findOne(['name' => 'Belize'])->id,
                32,
                'belize_2.png'
            ],
            [
                'Solo-ish Belize',
                787,
                "Dive into the heart of Belize on this Solo-ish adventure. From tortilla-making to exploring sacred Mayan caves and relaxing in Caye Caulker, experience Belize in a way that connects you to the Earth and other travelers.",
                'Solo-ish Adventures',
                'Standard',
                '3 - Average',
                'Small Group',
                '18+',
                '2025-08-16',
                \common\models\Country::findOne(['name' => 'Belize'])->id,
                7,
                'belize_3.png',
            ],
            [
                'Costa Rica Quest',
                824,
                "Nature called you to Costa Rica — now here you are, suspended in the jungle canopy, locking eyes with a curious monkey. This action-packed tour is perfect for the adventurer with limited time who wants to explore Costa Rica’s natural diversity.",
                'Classic',
                'Standard',
                '2 - Light',
                'Small Group',
                '12+',
                '2025-07-17',
                \common\models\Country::findOne(['name' => 'Costa Rica'])->id,
                9,
                'costa_rica_1.png'
            ],
            [
                'Costa Rica Adventure',
                1312,
                "Taste Costa Rica’s highlights with a spicy mix of hidden treasures. From volcanoes to beaches, this adventure offers a perfect balance of guided excursions and free time, with optional adrenaline-filled or relaxing activities.",
                'Classic',
                'Standard',
                '3 - Average',
                'Small Group',
                '12+',
                '2025-08-11',
                \common\models\Country::findOne(['name' => 'Costa Rica'])->id,
                16,
                'costa_rica_2.png'
            ],
            [
                'Costa Rica: Ocean Waves & Sunsets',
                562,
                "Hit two of Costa Rica's famed features — volcanoes and beaches — on this exciting trip that isn’t too hard on the wallet. Optional adventures, included transport and lodging, and expert guidance pack eight days with unforgettable experiences.",
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-08-23',
                \common\models\Country::findOne(['name' => 'Costa Rica'])->id,
                8,
                'costa_rica_3.png'
            ],
            [
                'Cuban Rhythms: Beachfronts & Havana Vibes',
                454,
                "Journey through Trinidad and Old Havana with music pouring from every corner. This fast-paced adventure includes beach time, cultural immersion in homestays, and vibrant nightlife — all for young, budget-minded travelers.",
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-07-20',
                \common\models\Country::findOne(['name' => 'Cuba'])->id,
                8,
                'cuba_1.png'
            ],
            [
                'Highlights of Cuba',
                639,
                "Short but rich, this 6-day tour explores Cuba’s culture, from the Bay of Pigs to the mountains. Enjoy immersive homestays, national parks, and colonial towns like Trinidad and Cienfuegos.",
                'Classic',
                'Standard',
                '2 - Light',
                'Small Group',
                '12+',
                '2025-08-30',
                \common\models\Country::findOne(['name' => 'Cuba'])->id,
                6,
                'cuba_2.png'
            ],
            [
                'Treasures of Cuba',
                1259,
                "Travel deep into Cuba’s eastern heart — Santiago de Cuba, Baracoa, and more. Visit revolutionary landmarks, explore cobbled towns, and stay in homestays for a fully immersive 15-day cultural journey.",
                'Classic',
                'Standard',
                '3 - Average',
                'Small Group',
                '12+',
                '2025-07-12',
                \common\models\Country::findOne(['name' => 'Cuba'])->id,
                15,
                'cuba_3.png'
            ],
            [
                'Volcano Trail: Waves & Local Ways',
                959,
                "Explore Guatemala, Honduras, El Salvador, Nicaragua, and Costa Rica in 17 days. Stay in a community guesthouse on Ometepe, ride local transport, and enjoy vibrant culture and beach vibes. Perfect for budget-minded young travelers.",
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-07-16',
                \common\models\Country::findOne(['name' => 'El Salvador'])->id,
                17,
                'el-salvador_1.png'
            ],
            [
                'Central American Journey: Rainforests & Ruins',
                2357,
                "Epic 32-day trip across seven countries in Central America — from Mexico to Costa Rica. Includes Mayan villages, rainforests, ruins, and coastlines on both oceans. Ideal for adventurous young travelers who want a full regional experience.",
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-11-27',
                \common\models\Country::findOne(['name' => 'El Salvador'])->id,
                32,
                'el-salvador_2.png'
            ],
            [
                'Central America Escape: Guatemala to Costa Rica',
                959,
                "Same itinerary as 'Volcano Trail', but open to travelers 12+. Enjoy the beauty of Central America with cultural immersion, guesthouse stays, tropical scenery and lively beach towns. Great for families or classic travelers.",
                'Classic',
                'Basic',
                '2 - Light',
                'Small Group',
                '12+',
                '2025-08-22',
                \common\models\Country::findOne(['name' => 'El Salvador'])->id,
                17,
                'el-salvador_3.png'
            ],
            [
                'Volcano Trail: Waves & Local Ways',
                959,
                "From the laid-back vibes and waves of the Pacific Coast to tropical rainforests alive with jungle melodies, take the road less travelled on this trip through Guatemala, Honduras, El Salvador, Nicaragua, and Costa Rica with other travellers your own age. This is one of our most exciting trips, filled with breathtaking scenery and a chance to experience local culture with a two-night community guesthouse stay on the island of Ometepe. Enjoy a blend of public and private transportation, which not only keeps costs down but also gives you a chance to really meet the locals.",
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-07-16',
                \common\models\Country::findOne(['name' => 'Guatemala'])->id,
                17,
                'guatemala_1.png'
            ],
            [
                'Central America Escape: Guatemala to Costa Rica',
                959,
                "Soak up the authentic local cultures of Central America on this 17-day whirlwind trip of entrancing scenery and laid-back vibes. Enjoy a blend of public and private transportation as you traverse the Pacific Coast, tropical rainforests, and roads less travelled through Guatemala, Honduras, El Salvador, Nicaragua, and Costa Rica. From a community guesthouse stay on the island of Ometepe to beach time in El Tunco, get ready for infinite memories to be made along the way.",
                'Classic',
                'Basic',
                '2 - Light',
                'Small Group',
                '12+',
                '2025-08-22',
                \common\models\Country::findOne(['name' => 'Guatemala'])->id,
                17,
                'guatemala_2.png'
            ],
            [
                'Central American Journey: Rainforests & Ruins',
                2357,
                "Escape the resorts and discover something extraordinary in Central America. Visit seven countries on this adventure and experience mighty ruins, clear Caribbean waters, Pacific waves, rainforests, and breathtaking scenery along the way. Explore indigenous Mayan villages and meet locals for an immersive experience that few travellers get to know. While you're free to choose your own adventure, your accommodation and transportation are included. Our expert CEOs will help you make the most of your time. Take a trip that's packed with all the things you need and nothing you don't – 32 days of maximum adventure at minimum cost.",
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-11-27',
                \common\models\Country::findOne(['name' => 'Guatemala'])->id,
                32,
                'guatemala_3.png'
            ],
            [
                'Volcano Trail: Waves & Local Ways',
                959,
                'From the laid-back vibes and waves of the Pacific Coast to tropical rainforests alive with jungle melodies, take the road less travelled on this trip through Guatemala, Honduras, El Salvador, Nicaragua, and Costa Rica with other travellers your own age. This is one of our most exciting trips, filled with breathtaking scenery and a chance to experience local culture with a two-night community guesthouse stay on the island of Ometepe. Enjoy a blend of public and private transportation, which not only keeps costs down but also gives you a chance to really meet the locals.',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-07-16',
                \common\models\Country::findOne(['name' => 'Honduras'])->id,
                17,
                'honduras_1.png'
            ],
            [
                'Central American Journey: Rainforests & Ruins',
                2357,
                'Escape the resorts and discover something extraordinary in Central America. Visit seven countries on this adventure and experience mighty ruins, clear Caribbean waters, Pacific waves, rainforests, and breathtaking scenery along the way. Explore indigenous Mayan villages and meet locals for an immersive experience that few travellers get to know. While you\'re free to choose your own adventure, your accommodation and transportation are included. Our expert CEOs will help you make the most of your time. Take a trip that\'s packed with all the things you need and nothing you don\'t – 32 days of maximum adventure at minimum cost.',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-11-27',
                \common\models\Country::findOne(['name' => 'Honduras'])->id,
                32,
                'honduras_2.png'
            ],
            [
                'Central America Escape: Guatemala to Costa Rica',
                959,
                'Soak up the authentic local cultures of Central America on this 17-day whirlwind trip of entrancing scenery and laid-back vibes. Enjoy a blend of public and private transportation as you traverse the Pacific Coast, tropical rainforests, and roads less travelled through Guatemala, Honduras, El Salvador, Nicaragua, and Costa Rica. From a community guesthouse stay on the island of Ometepe to beach time in El Tunco, get ready for infinite memories to be made along the way.',
                'Classic',
                'Basic',
                2,
                'Small Group',
                '12+',
                '2025-08-22',
                \common\models\Country::findOne(['name' => 'Honduras'])->id,
                17,
                'honduras_3.png'
            ],
            [
                'Central American Journey: Rainforests & Ruins',
                2357,
                'Escape the resorts and discover something extraordinary in Central America. Visit seven countries on this adventure and experience mighty ruins, clear Caribbean waters, Pacific waves, rainforests, and breathtaking scenery along the way. Explore indigenous Mayan villages and meet locals for an immersive experience that few travellers get to know. While you\'re free to choose your own adventure, your accommodation and transportation are included.',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-11-27',
                \common\models\Country::findOne(['name' => 'Mexico'])->id,
                32,
                'mexico_1.png'
            ],
            [
                'Mexico City to Oaxaca: Pottery & Aztec Pyramids',
                787,
                'This short but oh-so sweet trip through Central Mexico captures some of the best parts of the country\'s culture, landscapes, and tasty culinary traditions. You’ll visit the massive pyramids at Teotihuacán, then Puebla, famous for talavera pottery, and wrap up in Oaxaca with food, culture, and alebrijes.',
                'Classic',
                'Standard',
                2,
                'Small Group',
                '12+',
                '2025-08-30',
                \common\models\Country::findOne(['name' => 'Mexico'])->id,
                7,
                'mexico_2.png'
            ],
            [
                'Viva Mexico: Ancient Ruins & the Mayan Riviera',
                1087,
                'This 14-day adventure through the heart of Mexico has so much to love. From buzzing Mexico City to Tulum\'s beaches, explore ruins like Palenque and Chichen Itzá, jungle waterfalls, and eat your way through tacos and mole. Includes Mayan traditions and friendly locals.',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-07-13',
                \common\models\Country::findOne(['name' => 'Mexico'])->id,
                14,
                'mexico_3.png'
            ],
            [
                'Volcano Trail: Waves & Local Ways',
                959,
                'From the laid-back vibes and waves of the Pacific Coast to tropical rainforests alive with jungle melodies...',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-07-16',
                \common\models\Country::findOne(['name' => 'Nicaragua'])->id,
                17,
                'nicaragua_1.png'
            ],
            [
                'Central American Journey: Rainforests & Ruins',
                2357,
                'Escape the resorts and discover something extraordinary in Central America...',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-11-27',
                \common\models\Country::findOne(['name' => 'Nicaragua'])->id,
                32,
                'nicaragua_2.png'
            ],
            [
                'Central America Escape: Guatemala to Costa Rica',
                959,
                'Soak up the authentic local cultures of Central America on this 17-day whirlwind trip...',
                'Classic',
                'Basic',
                2,
                'Small Group',
                '12+',
                '2025-08-22',
                \common\models\Country::findOne(['name' => 'Nicaragua'])->id,
                17,
                'nicaragua_3.png'
            ],
            [
                 'Sailing the Canary Islands',
                 959,
                 'A yacht adventure is the ideal way to experience what many consider the world\'s most beautiful islands: the Canary Islands. Sail for seven days aboard our 17m (57 ft) yacht, with time for hiking, snorkeling and relaxing. Explore historical sites and cafe-lined harbours, and dine on fresh seafood.',
                 'Marine',
                 'Standard',
                 '3 - Average',
                 'Small Group',
                 '16+',
                 '2025-12-06',
                \common\models\Country::findOne(['name' => 'Canary Islands'])->id,
                 7,
                'canary-islands_1.png'
            ],
            [
                'Mont Blanc Explorer',
                1762,
                'Towering above the Alps, Mont Blanc commands respect. This trip puts committed travellers with excellent fitness on intimate terms with the ceiling of Europe, rewarding them with strolls through alpine villages, hearty dinners, relaxing spa visits, and jaw-droppingly beautiful mountain scenery.',
                'Active',
                'Standard',
                '4 - Demanding',
                'Small Group',
                '12+',
                '2025-07-12',
                \common\models\Country::findOne(['name' => 'France'])->id,
                8,
                'france_1.png'
            ],
            [
                'Mediterranean Express: Rivieras & Railroads',
                1364,
                'Quick and affordable seven-day tour from Rome to Barcelona, exploring Nice, Pisa, Gaudí’s architecture, and local food while travelling mostly by train, making the journey part of the experience.',
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-07-12',
                \common\models\Country::findOne(['name' => 'France'])->id,
                7,
                'france_2.png'
            ],
            [
                'Berlin to Paris: Bike Rides & Big Nights',
                1049,
                'Fast-paced six-day adventure across four countries from Berlin to Paris, including bike tours, nightlife in Amsterdam, and the romance of Bruges, designed for young, budget-minded travellers.',
                '18-to-Thirtysomethings',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-39',
                '2025-07-12',
                \common\models\Country::findOne(['name' => 'France'])->id,
                6,
                'france_3.png'
            ],
            [
                'Trekking Mont Blanc',
                2039,
                'Challenging 10-day trekking adventure across France, Italy, and Switzerland along the Tour du Mont Blanc, with glacier views, alpine meadows, and authentic mountain cuisine while conquering one of the world\'s premier hiking routes.',
                'Active',
                'Basic',
                '5 - Challenging',
                'Small Group',
                '12+ (under 18 accompanied by adult)',
                '2025-09-06',
                \common\models\Country::findOne(['name' => 'France'])->id,
                10,
                'france_1.png'
            ],
            [
                'Greek Island Hopping: Paros, Ios & Santorini Sunsets',
                1189,
                'All aboard for this six-day Greek Islands hopping adventure that’ll have you cruising the sparkling blue of the Mediterranean, and experiencing what the good life is all about. You’ll stroll past white sugar-cube houses in Naousa, kick back on seven different beaches on the island of Ios, and stare out into landscapes so beautiful you’ll swear they couldn’t be real. And with fresh feta and fish everywhere you go, this trip will have every one of your senses feeling oh-so satisfied.',
                '18-to-Thirtysomethings',
                'Basic',
                3,
                'Small Group',
                '18-39',
                '2025-07-09',
                \common\models\Country::findOne(['name' => 'Greece'])->id,
                7,
                'greece_1.png'
            ],
            [
                'Sailing Greece - Santorini to Santorini',
                1494,
                'A yacht adventure is the ideal way to experience what many consider the world’s most beautiful islands in Greece. Sail aboard our all-new, state-of-the-art 57 ft yachts, with time for hiking, snorkelling, and relaxing. Explore ancient archaeological sites and taverna-lined harbours, dine on fresh seafood and don’t forget to try the Ouzo! This 10-day round trip from Santorini will give you the chance to explore some of the treasures of the Greek Islands.',
                'Marine',
                'Standard',
                3,
                'Small Group',
                '16+',
                '2025-07-22',
                \common\models\Country::findOne(['name' => 'Greece'])->id,
                10,
                'greece_2.png'
            ],
            [
                'Highlights of the Greek Islands',
                1679,
                'Paradise lovers and beach enthusiasts, this one’s for you: eight days island hopping from Athens to the most incredible destinations in the Greek islands, ending in Santorini. Ancient sun-bleached ruins, piercing blue skies, and the balmy Aegean Sea provide the stunning natural backdrop for this trip that’s packed with culture, local music, tasty cuisine, and activities for the mind, body, and soul.',
                'Classic',
                'Standard',
                3,
                'Small Group',
                '12+',
                '2025-07-11',
                \common\models\Country::findOne(['name' => 'Greece'])->id,
                8,
                'greece_3.png'
            ],
            [
                'Highlights of Ireland',
                2159,
                'We’re all a little bit Irish come March 17, but if you’re in the market for something more meaningful than a pint of green beer, hop aboard this delightful nine-day adventure to the Emerald Isle. Cliffs of Moher, Ring of Kerry, traditional music in a local pub... seriously, it doesn’t get much more quintessentially Irish than this. We mix the essential sites and time in the villages to really round out the experience. Even if Ireland isn’t the Old Country for you, this trip will make you feel as though you’re back home.',
                'Classic',
                'Standard',
                2,
                'Small Group',
                '12+',
                '2025-10-04',
                \common\models\Country::findOne(['name' => 'Ireland'])->id,
                9,
                'ireland_1.png'
            ],
            [
                'Journeys: Iconic Ireland',
                2987,
                'A land of ancient legends, epic folktales, and grand traditions, Ireland is a destination that will truly transport you back in time. Uncover Celtic culture and admire medieval architecture across the stunning countryside, and delve into historic Dublin and the "rebel city" of Cork. Eat, dance, and sing with locals—even kiss the Blarney Stone—as you follow the roots of Irish culture to its core and come home with some Irish ballads of your own.',
                'National Geographic Journeys',
                'Upgraded',
                2,
                'Small Group',
                '12+',
                '2025-10-04',
                \common\models\Country::findOne(['name' => 'Ireland'])->id,
                9,
                'ireland_2.png'
            ],
            [
                'Highlights of Portugal',
                1319,
                'In Portugal, the sun is bright, the food is delicious, and the living is easy. Wander the hilly streets of coastal Lisbon, munch on a custard tart while gazing at sun-dappled architecture, and get your fill of history and culture at UNESCO World Heritage Sites like the Monastery of Batalha, Coimbra University, and the picturesque town of Sintra (optional). End the tour in Porto, where the majestic Douro Valley begs for you to lounge back with a glass of port wine in hand. Felicidades! And welcome to Portugal.',
                'Classic',
                'Standard',
                2,
                'Small Group',
                '12+',
                '2025-11-02',
                \common\models\Country::findOne(['name' => 'Portugal'])->id,
                7,
                'portugal_1.png'
            ],
            [
                'Journeys: Discover Portugal',
                2033,
                'On the western edge of mainland Europe, Portugal packs an alluring punch for curious travellers. Embark on an exploration rich in scenic beauty, fascinating history, and vibrant cultural traditions. Venturing from ancient streets and meandering rivers to an array of UNESCO World Heritage sites, encounter the multilayered legacies of Portuguese royalty and Romantics, the Knights Templar and Franciscan monks—and meet port wine makers, cork farmers, and fado folk singers along the way.',
                'National Geographic Journeys',
                'Upgraded',
                2,
                'Small Group',
                '12+',
                '2025-10-24',
                \common\models\Country::findOne(['name' => 'Portugal'])->id,
                8,
                'portugal_2.png'
            ],
            [
                'Hiking in Madeira',
                1179,
                'Immerse yourself in Madeira’s mesmerizing flavours, volcanic landscapes, and rich culture and history on this six-day hiking adventure across the island’s rugged terrain. From summiting Pico do Arieiro to hiking the Larano Trail and the levadas of Paul da Serra, experience diverse flora, dramatic cliffs, and breathtaking Atlantic views while exploring the subtropical rainforests and volcanic peaks of this unique Portuguese island.',
                'Active',
                'Standard',
                4,
                'Small Group',
                '12+',
                '2025-12-06',
                \common\models\Country::findOne(['name' => 'Portugal'])->id,
                6,
                'portugal_3.png'
            ],
            [
                'Absolute Turkey',
                1574,
                'This comprehensive tour of Turkey combines history and beaches, man-made wonders and natural phenomena, as well as a vibrant and welcoming culture. Begin your trip roaming the palaces and mosques of Istanbul before journeying into the bizarre as you explore otherworldly Cappadocia. From the amazing white cliff waterfalls of Pamukkale to the bustling bazaars of Istanbul, our local CEOs (Chief Experience Officers) will show you the region’s hidden gems and make sure your trip burns brightly in your memory long after you\'ve left this crossroads of Asia and Europe.',
                'Classic',
                'Standard',
                2,
                'Small Group',
                '12+',
                '2025-07-20',
                \common\models\Country::findOne(['name' => 'Turkey'])->id,
                15,
                'turkey_1.png'
            ],
            [
                'Highlights of Turkey',
                1279,
                'Dive deep into Turkey\'s most iconic treasures on this unforgettable eight-day adventure, packed with rich history, jaw-dropping landscapes, and mouthwatering cuisine. Wander through the ancient cities of Troy and Ephesus, delve into the mysterious underground city of Kaymakli, and explore Cappadocia\'s surreal, otherworldly terrain. Top it all off with a cozy dinner with a local family for a true taste of Turkish hospitality. Starting and ending in the vibrant streets of Istanbul, this trip will leave you craving more of Turkey\'s magic.',
                'Classic',
                'Standard',
                3,
                'Small Group',
                '12+',
                '2025-10-31',
                \common\models\Country::findOne(['name' => 'Turkey'])->id,
                8,
                'turkey_2.png'
            ],
            [
                'Turkey: Coastlines & Cappadocia',
                1279,
                'White cliffs and bright blue travertines of Pamukkale and the glimmering Blue Mosque, experience the best of Turkey\'s historical highlights and natural wonders in one incredible tour. Begin your trip roaming the palaces of Istanbul before journeying into the underground cities and fairy chimneys of Cappadocia. Using public buses and budget accommodation helps you meet locals and keep costs low. From the ancient Roman streets of Ephesus to bustling bazaars, spend 15 days discovering the culture and natural beauty of this fascinating region.',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-10-11',
                \common\models\Country::findOne(['name' => 'Turkey'])->id,
                15,
                'turkey_3.png'
            ],
            [
                'Croatia: Walking & Island-Hopping Along the Dalmatian Coast',
                3374,
                'Explore Croatia’s stunning coastline on this nine-day adventure through historic towns and Adriatic islands. Discover Dubrovnik by foot, kayak, and cable car, island-hop to Korčula and Hvar, and sail by private boat to the Pakleni Islands for swimming and walking. Wander Split’s old town and hike to the Krka Waterfalls. With a perfect mix of action, culture, and cuisine, this premium small-group trip blends comfort with active exploration along the Dalmatian Coast.',
                'The Geluxe Collection',
                'Upgraded',
                3,
                'Small Group',
                '18+',
                '2025-08-02',
                \common\models\Country::findOne(['name' => 'Croatia'])->id,
                9,
                'croatia_1.png'
            ],
            [
                'Southern Europe: Croatia, Montenegro & Ancient Greece',
                1469,
                '12 days, hostel-based adventure from Dubrovnik to Athens. Croatia, Montenegro, Albania, and Greece with sunrise hike to Kotor fortress, Skadar Lake, Delphi ruins, Parthenon, Acropolis, and Temple of Zeus.',
                'Roamies by Hostelworld & CanadaWay',
                'Basic',
                2,
                'Small Group',
                '18-35',
                '2025-07-14',
                \common\models\Country::findOne(['name' => 'Croatia'])->id,
                12,
                'croatia_2.png'
            ],
            [
                'The Best of Eastern Europe',
                2399.00,
                'From fairytale Czech towns to Budapest, the Pearl of the Danube, experience the unique culture, food, and history of Eastern Europe. This two-week trip through six Eastern European countries offers an intriguing combination of urban centres, village life, and outdoor pursuits. Visit castles, churches, and romantic town squares, indulging in Berlin’s café culture and Prague’s beer.',
                'Classic',
                'Standard',
                2,
                'Small Group',
                '12+',
                '2025-10-26',
                \common\models\Country::findOne(['name' => 'Germany'])->id,
                14,
                'germany_1.png'
            ],
            [
                'Journeys: Explore Central Europe',
                2323.00,
                'Delve into the cultural wonders of Central Europe on a survey of its most celebrated landmarks, from Germany’s iconic Brandenburg Gate to Czechia’s centuries-old Charles Bridge. Step into the past in Berlin, Vienna, Prague, Budapest, and the Bohemian countryside, exploring ancient castles and historic districts alongside local historians. Taste culinary specialties, discover contemporary art, and experience the ever-evolving vibrancy of these storied places.',
                'National Geographic Journeys',
                'Upgraded',
                2,
                'Small Group',
                '12+',
                '2025-10-11',
                \common\models\Country::findOne(['name' => 'Germany'])->id,
                9,
                'germany_2.png'
            ],
            [
                'Essential Western Europe: Amsterdam, Berlin & Epic Views',
                1504.00,
                "Amsterdam. Prague. Vienna. Berlin. Munich. If these names alone have you squealing with excitement, this 10-day adventure will have you dancing down cobblestone streets. You’ll soak up the history and booming art scene of Berlin, and have your mind blown by the architecture of Prague and Vienna. Want epic natural views? You got it. Walk the highest natural rock bridge in all of Europe at the Pravčická Gate, and hike along a ridiculously scenic mountain lake on the way to Salzburg. Staying in awesome hostels along the way, this adventure is the best of Western Europe, all wrapped up into one.",
                'Roamies by Hostelworld & CanadaWay',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-35',
                '2025-08-10',
                \common\models\Country::findOne(['name' => 'Germany'])->id,
                10,
                'germany_3.png'
            ],
            [
                'Hiking Southern Iceland',
                2159.00,
                "Iceland may appear small on the map, but in person its enormous and cinematic landscapes barely feel like Earth at all. Get outdoors and into the action on this six-day active adventure through some of the most epic scenery in the entire country. Hike to the bases of pounding waterfalls, breathtaking in their strength. Travel through landscapes filled with towering peaks, massive glaciers, sprawling icefields, black sand beaches, and wild fjords. Set off on some of the best hikes in the region through spots like Múlagljúfur Canyon, the Skaftafell Glacier, Mt. Laki, and Brennisteinsalda volcano where you can bathe in a natural hot pool. Start and finish the trip in weirdly wonderful Reykjavík and discover how the people lucky enough to call this place home live full-time.",
                'Active',
                'Standard',
                '4 - Demanding',
                'Small Group',
                '12+',
                '2025-09-20',
                \common\models\Country::findOne(['name' => 'Iceland'])->id,
                6,
                'iceland_1.png'
            ],
            [
                'Trekking Eastern Iceland',
                1879.00,
                "Dotted with humbling fjords, breathtaking waterfalls, and no-filter-needed fishing villages, Eastern Iceland is an adventure unto itself. Experience this otherworldly region in its truest form on this six-day trek that’s guided by one of our expert CEOs (Chief Experience Officers) from start to finish.",
                'Active',
                'Standard',
                '4 - Demanding',
                'Small Group',
                '12+',
                '2025-07-20',
                \common\models\Country::findOne(['name' => 'Iceland'])->id,
                6,
                'iceland_2.png'
            ],
            [
                'Western and Central Europe: Venice, the Alps & the Flavours of Rome',
                1189.00, // USD, текущая цена со скидкой
                "Make the epic trip from Germany to Italy on this eight-day hostel-based adventure. Explore Munich, Innsbruck, Venice, Florence, and Rome with foodie tours, scenic hikes, and authentic local experiences along the way.",
                'Roamies by Hostelworld & CanadaWay',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-35',
                '2025-07-22',
                \common\models\Country::findOne(['name' => 'Italy'])->id,
                8,
                'italy_1.png'
            ],
            [
                'Gotta-See Europe: Germany, Austria, Italy',
                2719.00,
                "From Amsterdam to Rome, this 17-day hostel-based adventure takes you through some of Europe’s best destinations. Explore the vibrant cities of Berlin, Prague, Vienna, Salzburg, Venice, Florence, and Rome with plenty of scenic hikes, cultural tours, and of course, mouth-watering cuisine.",
                'Roamies by Hostelworld & CanadaWay',
                'Basic',
                '2 - Light',
                'Small Group',
                '18-35',
                '2025-10-05',
                \common\models\Country::findOne(['name' => 'Italy'])->id,
                17,
                'italy_2.png'
            ],
            [
                'Total Europe: Berlin, Prague & the Tastes of Italy',
                3359,
                '23 days. 13 of Europe’s most iconic cities. You in? Yeah you are. Make your way from Amsterdam to Dubrovnik on this hostel-based adventure.',
                'Roamies by Hostelworld & CanadaWay',
                'Basic',
                2,  // Light
                'Small Group',
                '18-35',
                '2025-07-13',
                \common\models\Country::findOne(['name' => 'Italy'])->id,
                23,
                'italy_3.png'
            ],
            [
                'Mediterranean Express: Rivieras & Railroads',
                1364,
                '7 days, Rome to Barcelona. Jump on this quick seven-day tour of some of Europe\'s greatest cities. See Nice, Pisa, Gaudí’s architecture, and more!',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-07-12',
                \common\models\Country::findOne(['name' => 'Spain'])->id,
                7,
                'spain_1.png'
            ],
            [
                'Spain & Portugal: Flamenco & Tapas',
                1463,
                '10 days, Barcelona to Lisbon. Experience Spain and Portugal with art, culture, tapas, and nightlife. City-hopping through Iberia by local buses and trains.',
                '18-to-Thirtysomethings',
                'Basic',
                2,
                'Small Group',
                '18-39',
                '2025-09-19',
                \common\models\Country::findOne(['name' => 'Spain'])->id,
                10,
                'spain_2.png'
            ],
            [
                'Solo-ish Spain',
                2137,
                '9 days, Barcelona to Seville. Explore the best of Spain with tapas, paella cooking classes, and vibrant cities like Granada and Seville. A solo traveller\'s dream!',
                'Solo-ish Adventures',
                'Standard',
                2,  // Light
                'Small Group',
                '18-39',
                '2025-08-30',
                \common\models\Country::findOne(['name' => 'Spain'])->id,
                9,
                'spain_3.png'
            ],
            [
                'Highlights of Scotland',
                2137,
                '7 days, Edinburgh to Glasgow City. Explore the best of Scotland from the famous Loch Ness to the Jacobite Steam Train. A trip for history buffs, whisky lovers, and fans of beautiful landscapes!',
                'Classic',
                'Standard',
                2,  // Light
                'Small Group',
                '12+',
                '2025-08-17',
                \common\models\Country::findOne(['name' => 'United Kingdom'])->id,
                7,
                'united-kingdom_1.png'
            ],
            [
                'Highlights of Ireland',
                2159,
                '9 days, Dublin to Belfast. Explore the Cliffs of Moher, Ring of Kerry, Giant\'s Causeway, Bushmills Distillery, and traditional Irish culture from south to north.',
                'Classic',
                'Standard',
                2, // Light
                'Small Group',
                '12+',
                '2025-10-04',
                \common\models\Country::findOne(['name' => 'United Kingdom'])->id,
                9,
                'united-kingdom_2.png'
            ],
            [
                'The Scottish Isles: An Expedition Through History & Highlands',
                4849,
                '10 days, Glasgow to Leith. Expedition cruise through Hebrides, St. Kilda, Thurso, Orkney, and Shetland Islands with wildlife, puffins, Viking sites, and rugged coastlines.',
                'Marine',
                'Standard', // Если у Marine туров нет отдельного service_level, укажите NULL
                2, // Light
                'Small Ship Expedition', // Если в системе есть trip_type для Marine
                '10+',
                '2026-04-28',
                \common\models\Country::findOne(['name' => 'United Kingdom'])->id,
                10,
                'united-kingdom_3.png'
            ]
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%tour}}');
    }
}
