version: '3.2'

name: yii2_itr_template

services:

  app:
    build: .
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - composercache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
      - storage:/appstorage
    depends_on:
      - mysql
    restart: always

  # Use HeidiSQL for connecting to db
  mysql:
    image: mysql:8.0
    ports:
      - 23306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=itr_yii2_template
      - MYSQL_USER=itr_yii2_template
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  mysql:
  storage:
  composercache: