openapi: 3.0.3
info:
  title: IT Result Yii2 Template
  description: |-
    Пример оформления JSON API документации
  version: 1.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:20080/api/
tags:
- name: host
  description: Межхостовые взаимодействия
paths:
  /host/v1/site/index:
    post:
      tags:
      - host
      summary: SiteIndex
      description: SiteIndex
      operationId: SiteIndex
      requestBody:
        description: API Example
      responses:
        '200':
          description: Successful operation